version: '3.7'

services:
  db:
    container_name: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

  mongo-express:
      container_name: mongo-express
      image: mongo-express
      depends_on:
        - db
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongo-dev
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=tribes
      ports:
        - '8081:8081'
      volumes:
        - mongo:/data/db

  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8888
      --access-logfile -
      --reload
      "snakeeyes.app:create_app()"
    volumes:
      - ".:/snakeeyes"
    depends_on:
      - "db"
      - "redis"
    ports:
      - "8888:8888"
    env_file:
      - '.env'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery worker -l info -A snakeeyes.blueprints.contact.tasks
    env_file:
      - '.env'
    depends_on:
      - "web"
    volumes:
      - '.:/snakeeyes'

volumes:
  mongo:
  redis: